#!/bin/bash

# Define an array of machine names
machines=("001UP" "002" "003" "004" "005" "006" "007" "008" "009" "010" "011" "012")

for i in $(seq 1 1 3); do
    # Loop through the array and access elements using indices
        echo " _______      ______      ______      ______      ______      ______      ______      ______      ______      ______      ______      ______"
        echo "|      |      |    |      |    |      |    |"
        echo "|${machines[j]} |      |${machines[j+1]} |      |${machines[j+2]} |      |${machines[j+3]} |      |${machines[j+4]} |      |${machines[j+5]} |      |${machines[j+6]} |      |${machines[j+7]} |      |${machines[j+8]} |      |${machines[j+9]} |      |${machines[j+10]} |      |${machines[j+11]} |"
        echo " ''''''      ''''''      ''''''      ''''''      ''''''      ''''''      ''''''      ''''''      ''''''      ''''''      ''''''      ''''''"
done
